name: Publish image to docker hub
on: # runs whenever a push is made PLUS every tuesday morning
  push:
    branches:
    - "latest"
  schedule:
    - cron: "0 0 * * 2" # runs on every tuesday at 00:00 => patchday

jobs:
  build-and-push-to-registry:
    name: Build docker image and push them to docker hub
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build the tagged Docker image
        shell: bash
        run: docker build -t ${{ github.repository_owner }}/$( echo ${{ github.repository }} | sed 's|.*/containered-||' ) .

      - name: Push the tagged Docker image
        shell: bash
        run: |
          docker login --username ${{ github.repository_owner }} --password ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ github.repository_owner }}/$( echo ${{ github.repository }} | sed 's|.*/containered-||' )
          docker logout
